// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rojwquyemtasasswptdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvandxdXllbXRhc2Fzc3dwdGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODI5NjgsImV4cCI6MjA3MDI1ODk2OH0.VPMSEPWYcSwSjdD_kt7zIcpBe7DUL4xNkWIe9hpHXxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});